platform: linux
image_resource:
  type: registry-image
  source:
    repository: rust
    tag: 1.56

inputs:
  - name: artifacts

caches:
  # yeah, I'm not sure how I feel about caching the registry like this,
  # but concourse only allows relative paths instead of absolute ones
  - path: ../../../usr/local/cargo/registry

run:
  dir: artifacts
  path: scripts/run_all
