#!/bin/sh
if [ $# -eq 0 ]
  then echo "Usage: ./scripts/mem [day]\ne.g. ./scripts/mem 001"
  exit 1;
fi

cargo run --example 2>&1 | grep "${1}_profile" | while read -r line; do
  cargo run --example $line
  heaptrack "target/debug/examples/${line}"
done
