#!/bin/sh
if [ $# -eq 0 ]
  then echo "Usage: ./scripts/run [day]\ne.g. ./scripts/run 001"
  exit 1;
fi

example=$(find examples -type d -name "${1}*" -exec basename {} \;)

cargo run --example=$example --release
